openapi: '3.0.1'
info:
  title: XRS API Documentation
  version: '1.0.0'
security: []
components:
  schemas:
    DriverLogModified:
      properties:
        CoDriverName:
          type: "string"
          example: Jack
        CoDriverID:
          type: "string"
          example: Dr9878
        DistanceUnit:
          type: "string"
          example: Milles
        DriverConfirmed:
          type: "boolean"
          example: true
        DriverID:
          type: "string"
          example: DRV54
        DriverName:
          type: "string"
          example: John
        HOSRuleSet:
          type: "string"
          example: US 8/80 Day NC hrs.
        LogDetails:
          $ref: "#/components/schemas/DriverLogDetailModified"
          example:
    DriverLogDetailModified:
      properties:
        CityName:
          type: "string"
          example: Dallas
        Comment:
          type: "string"
          example: Comment
        Current:
          type: "boolean"
          example: true
        DriverID:
          type: "string"
          example: DR712
        EditedDate:
          type: string
          format: datetime
          nullable: true
          example: 2024-05-31 11:20:00
        EventType:
          type: "string"
          example: Driver duty status changed to Driving
        Latitude:
          type: number
          format: double
          example: 32.7830600
        LocationName:
          type: "string"
          example: 1km E Mississauga ON
        Longitude:
          type: number
          format: double
          example: -96.8066700
        ModifiedDate:
          type: string
          format: datetime
          nullable: true
          example: 2022-05-31 11:20:00
        RecordSID:
          type: "string"
          example: 65165
        RecordTime:
          type: string
          format: datetime
          example: 2024-05-31 11:20:00
        Remark:
          type: "string"
          example: Beginning of Restart Period
        RowID:
          type: "string"
          example: 654
        Sequence:
          type: "string"
          example: String
        SiteID:
          type: "string"
          example: 12
        StateName:
          type: "string"
          example: Texas
        Odometer:
          type: number
          format: float
          nullable: true
          example: 798123.321
